 resource_type = {
    use_item = 1,--使用道具
    gm_command = 2,--gm命令
    cangbaotu = 3,--藏宝图
    compounditem = 4,--合成物品
	dishaxing_extra	= 5, --地煞星额外
	dishaxing_kill	= 6,	--击杀地煞星
	dishaxing_fail	= 7,	--地煞星失败扣经验
	yao_wang_kill	= 8,	--击杀妖王
	yao_wang_fail	= 9,	--击杀妖王失败扣经验
	xiao_yao		= 10,	--击杀小妖
	xiao_yao_fail	= 11,	--击杀小妖失败
	xiao_wang_free	= 12, 	--释放的妖王获得的经验
	xiao_yao_free	= 13,	-- 释放的小妖获得的经验
	main_task		= 14,	--主线经验
	zuo_tian		= 15,	--做天
	pvp_copy_win	= 16,	--pvp副本战斗胜利经验
	use_gift		= 17,	--商城礼包经验
	guild_box_award	= 18,	--帮派强盗箱子的经验
	guild_boss_award= 19,	--帮派强盗击杀经验
	da_li_shi_right = 20,	--大理石答题对的经验
	da_li_shi_error	= 21,	--大理石答题错的经验
	liang_bai_hun_task = 22, --两百环任务经验
	zuo_tian_leader	 = 23,	--做天队长额外奖励
	gild_task		= 24,	--帮派任务
	shi_men_task	= 25,	--师门任务
	zhua_gui_task	= 26,	--抓鬼
	zhua_gui_task_leader = 27,	--抓鬼队长额外奖励
	da_yan_ta	= 28,		--大雁塔副本任务
	xun_fang	= 29,		--寻芳副本任务
    wishing = 30,           --许愿池
    alchemy_room = 31,      --炼金室
	rei_task	= 32,		--转生任务
	xiaoyao_away = 33,		--小妖逃跑
	yaowang_away = 34, 		--妖王逃跑
    branch_task  = 35,      --支线任务
    train_pet    = 36,      --宠物训练	
}

return resource_type